from app.core.categories import TransactionCategory as C
 
SEED_MERCHANT_MAP: dict[str, str] = {
    "swiggy": C.FOOD,
    "zomato": C.FOOD,
    "amazon": C.SHOPPING,
    "flipkart": C.SHOPPING,
    "myntra": C.SHOPPING,
    "irctc": C.TRAVEL,
    "makemytrip": C.TRAVEL,
    "uber": C.TRAVEL,
    "ola": C.TRAVEL,
    "rapido": C.TRAVEL,
    "netflix": C.SUBSCRIPTION,
    "spotify": C.SUBSCRIPTION,
    "hotstar": C.SUBSCRIPTION,
    "airtel": C.BILLS,
    "jio": C.BILLS,
    "vodafone": C.BILLS,
    "tata power": C.BILLS,
    "bescom": C.BILLS,
    "bigbasket": C.GROCERIES,
    "blinkit": C.GROCERIES,
    "zepto": C.GROCERIES,
    "dmart": C.GROCERIES,
    "apollo pharmacy": C.HEALTH,
    "practo": C.HEALTH,
    "pvr": C.ENTERTAINMENT,
    "inox": C.ENTERTAINMENT,
    "bookmyshow": C.ENTERTAINMENT,
    "zerodha": C.INVESTMENT,
    "groww": C.INVESTMENT,
    "upstox": C.INVESTMENT,
    "neft": C.TRANSFER,
    "imps": C.TRANSFER,
    "upi": C.TRANSFER,
}
