export const CATEGORIES = [
  {
    id: "dining",
    code: "CAT 001",
    label: "DINING",
    hint: "Swiggy, Zomato, Cafes",
    unselectedBg: "bg-orange-500/5 hover:bg-orange-500/12",
    codeColor: "text-orange-600",
    dotBorder: "border-orange-400",
    selectedBg: "bg-[#ea580c] text-white shadow-inner",
    selectedCodeColor: "text-orange-100",
    selectedDot: "bg-white",
  },
  {
    id: "travel",
    code: "CAT 002",
    label: "TRAVEL",
    hint: "Flights, Hotels, Trains",
    unselectedBg: "bg-sky-500/5 hover:bg-sky-500/12",
    codeColor: "text-sky-600",
    dotBorder: "border-sky-400",
    selectedBg: "bg-[#0284c7] text-white shadow-inner",
    selectedCodeColor: "text-sky-100",
    selectedDot: "bg-white",
  },
  {
    id: "groceries",
    code: "CAT 003",
    label: "GROCERY",
    hint: "Blinkit, Supermarkets",
    unselectedBg: "bg-emerald-500/5 hover:bg-emerald-500/12",
    codeColor: "text-emerald-600",
    dotBorder: "border-emerald-400",
    selectedBg: "bg-[#16a34a] text-white shadow-inner",
    selectedCodeColor: "text-emerald-100",
    selectedDot: "bg-white",
  },
  {
    id: "fuel",
    code: "CAT 004",
    label: "GAS & FUEL",
    hint: "Petrol, Daily Commute",
    unselectedBg: "bg-amber-500/6 hover:bg-amber-500/14",
    codeColor: "text-amber-700",
    dotBorder: "border-amber-400",
    selectedBg: "bg-[#d97706] text-white shadow-inner",
    selectedCodeColor: "text-amber-100",
    selectedDot: "bg-white",
  },
  {
    id: "online_shopping",
    code: "CAT 005",
    label: "SHOPPING",
    hint: "Amazon, Flipkart, Myntra",
    unselectedBg: "bg-purple-500/5 hover:bg-purple-500/12",
    codeColor: "text-purple-600",
    dotBorder: "border-purple-400",
    selectedBg: "bg-[#7c3aed] text-white shadow-inner",
    selectedCodeColor: "text-purple-100",
    selectedDot: "bg-white",
  },
  {
    id: "bills",
    code: "CAT 006",
    label: "UTILITIES",
    hint: "Bills, Wi-Fi, Mobile",
    unselectedBg: "bg-teal-500/5 hover:bg-teal-500/12",
    codeColor: "text-teal-600",
    dotBorder: "border-teal-400",
    selectedBg: "bg-[#0d9488] text-white shadow-inner",
    selectedCodeColor: "text-teal-100",
    selectedDot: "bg-white",
  },
];

export const OTHER_CATEGORIES_DROPDOWN = [
  { value: "entertainment", label: "Entertainment & OTT", hint: "Netflix, Movies" },
  { value: "health", label: "Health & Pharmacy", hint: "Apollo, PharmEasy" },
  { value: "education", label: "Education & Courses", hint: "Fees, Coaching" },
  { value: "international", label: "International Spends", hint: "Forex, Overseas" },
];
