export const TOP_MERCHANTS = [
  {
    id: "Flipkart",
    code: "MERCH 01",
    name: "FLIPKART",
    hint: "E-Commerce & Fashion",
    unselectedBg: "bg-[#2874f0]/6 hover:bg-[#2874f0]/14",
    codeColor: "text-[#2874f0]",
    dotBorder: "border-[#2874f0]/60",
    selectedBg: "bg-[#2874f0] text-white shadow-inner",
    selectedCodeColor: "text-blue-100",
    selectedDot: "bg-white",
  },
  {
    id: "Swiggy",
    code: "MERCH 02",
    name: "SWIGGY",
    hint: "Food & Instamart",
    unselectedBg: "bg-[#fc8019]/6 hover:bg-[#fc8019]/14",
    codeColor: "text-[#fc8019]",
    dotBorder: "border-[#fc8019]/60",
    selectedBg: "bg-[#fc8019] text-white shadow-inner",
    selectedCodeColor: "text-orange-100",
    selectedDot: "bg-white",
  },
  {
    id: "Myntra",
    code: "MERCH 03",
    name: "MYNTRA",
    hint: "Fashion & Lifestyle",
    unselectedBg: "bg-[#ff3f6c]/6 hover:bg-[#ff3f6c]/14",
    codeColor: "text-[#ff3f6c]",
    dotBorder: "border-[#ff3f6c]/60",
    selectedBg: "bg-[#ff3f6c] text-white shadow-inner",
    selectedCodeColor: "text-pink-100",
    selectedDot: "bg-white",
  },
  {
    id: "Zomato",
    code: "MERCH 04",
    name: "ZOMATO",
    hint: "Food & Dining",
    unselectedBg: "bg-[#e23744]/6 hover:bg-[#e23744]/14",
    codeColor: "text-[#e23744]",
    dotBorder: "border-[#e23744]/60",
    selectedBg: "bg-[#e23744] text-white shadow-inner",
    selectedCodeColor: "text-red-100",
    selectedDot: "bg-white",
  },
  {
    id: "Amazon",
    code: "MERCH 05",
    name: "AMAZON",
    hint: "All-in-one Shopping",
    unselectedBg: "bg-[#ff9900]/8 hover:bg-[#ff9900]/16",
    codeColor: "text-[#d97706]",
    dotBorder: "border-[#d97706]/60",
    selectedBg: "bg-[#232f3e] text-white shadow-inner",
    selectedCodeColor: "text-[#ff9900]",
    selectedDot: "bg-[#ff9900]",
  },
  {
    id: "Blinkit",
    code: "MERCH 06",
    name: "BLINKIT",
    hint: "Quick Commerce & Instant",
    unselectedBg: "bg-[#f7ce00]/15 hover:bg-[#f7ce00]/25",
    codeColor: "text-[#0c831f]",
    dotBorder: "border-[#0c831f]/60",
    selectedBg: "bg-[#f7ce00] text-neutral-950 shadow-inner",
    selectedCodeColor: "text-[#0c831f]",
    selectedDot: "bg-[#0c831f]",
  },
];

export const OTHER_MERCHANT_OPTIONS = [
  { value: "MakeMyTrip", label: "MakeMyTrip" },
  { value: "Uber", label: "Uber" },
  { value: "Tata Neu", label: "Tata Neu" },
  { value: "BookMyShow", label: "BookMyShow" },
  { value: "Zepto", label: "Zepto" },
];
