"""Added rewards, spends, and updated card model relationships

Revision ID: 4b8722640e11
Revises: c52328a7e437
Create Date: 2026-08-07 19:27:51.772921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8722640e11'
down_revision: Union[str, Sequence[str], None] = 'c52328a7e437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('annual_fee', sa.Numeric(), nullable=False),
    sa.Column('reward_unit', sa.String(), nullable=False),
    sa.Column('point_value_inr', sa.Numeric(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['card_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spend_tracker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('period_key', sa.String(), nullable=False),
    sa.Column('spend_amount', sa.Numeric(), nullable=False),
    sa.Column('reward_earned', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['reward_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'category', 'period_key', name='uq_spend_period')
    )
    op.add_column('cards', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cards', 'card_products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'product_id')
    op.drop_table('spend_tracker')
    op.drop_table('reward_cards')
    # ### end Alembic commands ###
