"""Added ON DELETE CASCADE in connected accounts

Revision ID: 56fd069257b7
Revises: 0cd143e99bc0
Create Date: 2026-07-31 20:50:31.001030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56fd069257b7'
down_revision: Union[str, Sequence[str], None] = '0cd143e99bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('connected_accounts_user_id_fkey'), 'connected_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'connected_accounts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connected_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('connected_accounts_user_id_fkey'), 'connected_accounts', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
