"""Edited connected_accounts table to add more fields

Revision ID: 5e5289024050
Revises: 4a614f76a8bf
Create Date: 2026-07-28 23:32:45.188275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e5289024050'
down_revision: Union[str, Sequence[str], None] = '4a614f76a8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('connected_accounts', sa.Column('encrypted_access_token', sa.String(), nullable=False))
    op.add_column('connected_accounts', sa.Column('encrypted_refresh_token', sa.String(), nullable=False))
    op.add_column('connected_accounts', sa.Column('scopes', sa.String(), nullable=False))
    op.add_column('connected_accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('connected_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('connected_accounts', 'token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('connected_accounts', 'access_token')
    op.drop_column('connected_accounts', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('connected_accounts', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('connected_accounts', 'token_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('connected_accounts', 'updated_at')
    op.drop_column('connected_accounts', 'created_at')
    op.drop_column('connected_accounts', 'scopes')
    op.drop_column('connected_accounts', 'encrypted_refresh_token')
    op.drop_column('connected_accounts', 'encrypted_access_token')
    op.drop_column('connected_accounts', 'email')
    # ### end Alembic commands ###
