"""Added merchants table

Revision ID: 67d541116686
Revises: 56fd069257b7
Create Date: 2026-08-02 13:32:57.995453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d541116686'
down_revision: Union[str, Sequence[str], None] = '56fd069257b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_category_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_category_map_merchant_key'), 'merchant_category_map', ['merchant_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_category_map_merchant_key'), table_name='merchant_category_map')
    op.drop_table('merchant_category_map')
    # ### end Alembic commands ###
