"""drop discovered_cards and pending_transactions

Revision ID: 67f412beca63
Revises: f92903e9ce14
Create Date: 2026-08-07 15:54:29.898275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67f412beca63'
down_revision: Union[str, Sequence[str], None] = 'f92903e9ce14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop child table first (has FK → discovered_cards)
    op.drop_index(op.f('ix_pending_transactions_discovered_card_id'), table_name='pending_transactions')
    op.drop_table('pending_transactions')
    # Drop parent table
    op.drop_index(op.f('ix_discovered_cards_user_id'), table_name='discovered_cards')
    op.drop_table('discovered_cards')
    # Drop the PostgreSQL enum type that was created with the table
    op.execute("DROP TYPE IF EXISTS discovered_card_status")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discovered_card_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('raw_email_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('transaction_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['discovered_card_id'], ['discovered_cards.id'], name=op.f('pending_transactions_discovered_card_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_transactions_pkey')),
    sa.UniqueConstraint('raw_email_id', name=op.f('pending_transactions_raw_email_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pending_transactions_discovered_card_id'), 'pending_transactions', ['discovered_card_id'], unique=False)
    op.create_table('discovered_cards',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_last4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'dismissed', name='discovered_card_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('discovered_cards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('discovered_cards_pkey'))
    )
    op.create_index(op.f('ix_discovered_cards_user_id'), 'discovered_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###
