"""drop card_network from cards

Revision ID: c52328a7e437
Revises: 67f412beca63
Create Date: 2026-08-07 16:06:26.961782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52328a7e437'
down_revision: Union[str, Sequence[str], None] = '67f412beca63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'card_network')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_network', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
