"""add card_products discovered_cards pending_transactions

Revision ID: f92903e9ce14
Revises: 67d541116686
Create Date: 2026-08-07 15:34:58.091048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92903e9ce14'
down_revision: Union[str, Sequence[str], None] = '67d541116686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_products',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('card_network', sa.String(), nullable=True),
    sa.Column('reward_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_card_products_bank_name'), 'card_products', ['bank_name'], unique=False)
    op.create_table('discovered_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('card_last4', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'dismissed', name='discovered_card_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_cards_user_id'), 'discovered_cards', ['user_id'], unique=False)
    op.create_table('pending_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('discovered_card_id', sa.Uuid(), nullable=False),
    sa.Column('raw_email_id', sa.String(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['discovered_card_id'], ['discovered_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_email_id')
    )
    op.create_index(op.f('ix_pending_transactions_discovered_card_id'), 'pending_transactions', ['discovered_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_transactions_discovered_card_id'), table_name='pending_transactions')
    op.drop_table('pending_transactions')
    op.drop_index(op.f('ix_discovered_cards_user_id'), table_name='discovered_cards')
    op.drop_table('discovered_cards')
    op.drop_index(op.f('ix_card_products_bank_name'), table_name='card_products')
    op.drop_table('card_products')
    # ### end Alembic commands ###
